language: objective-c
cache: bundle

before_script:
  - gem install luffa --no-document --env-shebang --no-prerelease
  - luffa authorize

script:
  - script/ci/travis/run.rb --tags @travis

notifications:
  email:
    - joshuajmoody@gmail.com
    - karl.krukow@xamarin.com
    - chris.fuentes@xamarin.com
    on_success: change
    on_failure: always
