<%

require 'run_loop'

ss_path = "./screenshots/"
FileUtils.rm_rf(ss_path)
FileUtils.mkdir(ss_path)

xamarin_dir = "#{ENV['HOME']}/.xamarin"
devices = {}
device_list = ['neptune', 'venus', 'earp', 'mars', 'saturn', 'pegasi', 'hat', 'erik', 'denis', 'uranus']
device_list.each do |device|
  dir = "#{xamarin_dir}/devices/#{device}"
  ip = IO.read("#{dir}/ip") if File.exists?("#{dir}/ip")
  udid = IO.read("#{dir}/udid") if File.exists?("#{dir}/udid")
  ht = {:dir => dir,
        :ip => ip,
        :udid => udid}
  devices[device.to_sym] = ht

  FileUtils.mkdir("./reports/#{device}") unless File.exists?("./reports/#{device}")
  FileUtils.mkdir("./reports/#{device}/screenshots") unless File.exists?("./reports/#{device}/screenshots")
end

if ENV["USER"] == "jenkins"
  formatter = "pretty"
  keep_sim_open_after = "0"
else
  formatter = "Slowhandcuke::Formatter"
  keep_sim_open_after = "1"
end

default_app = "./Products/app/CalSmoke-cal/CalSmoke-cal.app"
app = ENV["APP"] || ENV["APP_BUNDLE_PATH"] || default_app

%>

verbose: CALABASH_FULL_CONSOLE_OUTPUT=1 DEBUG=1
common: -f <%= formatter %> SCREENSHOT_PATH=<%= ss_path %>

reset_btw:    RESET_BETWEEN_SCENARIOS=1

app:          APP=<%= app %>

simulator:     -p app -p common --tags ~@device_only --tags ~@device NO_STOP=<%= keep_sim_open_after %>
default:       -p simulator

# required only for devices
bundle_id:    BUNDLE_ID=sh.calaba.CalSmoke-cal

device_common:  -p common -p bundle_id --tags ~@simulator --tags ~@simulator_only

neptune_common: DEVICE_TARGET=<%= devices[:neptune][:udid] %> DEVICE_ENDPOINT=<%= devices[:neptune][:ip] %> -p device_common
neptune:           -p neptune_common

venus_common:   DEVICE_TARGET=<%= devices[:venus][:udid] %>   DEVICE_ENDPOINT=<%= devices[:venus][:ip] %> -p device_common
venus:          -p venus_common

earp_common:   DEVICE_TARGET=<%= devices[:earp][:udid] %> DEVICE_ENDPOINT=<%= devices[:earp][:ip] %> -p device_common
earp:          -p earp_common

mars_common:   DEVICE_TARGET=<%= devices[:mars][:udid] %> DEVICE_ENDPOINT=<%= devices[:mars][:ip] %> -p device_common
mars:          -p mars_common

saturn_common:   DEVICE_TARGET=<%= devices[:saturn][:udid] %> DEVICE_ENDPOINT=<%= devices[:saturn][:ip] %> -p device_common
saturn:          -p saturn_common

pegasi_common:   DEVICE_TARGET=<%= devices[:pegasi][:udid] %> DEVICE_ENDPOINT=<%= devices[:pegasi][:ip] %> -p device_common
pegasi:          -p pegasi_common

hat:   DEVICE_TARGET=<%= devices[:hat][:udid] %> DEVICE_ENDPOINT=<%= devices[:hat][:ip] %> -p device_common
erik:   DEVICE_TARGET=<%= devices[:erik][:udid] %> DEVICE_ENDPOINT=<%= devices[:erik][:ip] %> -p device_common
denis: DEVICE_TARGET=<%= devices[:denis][:udid] %> DEVICE_ENDPOINT=<%= devices[:denis][:ip] %> -p device_common
uranus: DEVICE_TARGET=<%= devices[:uranus][:udid] %> DEVICE_ENDPOINT=<%= devices[:uranus][:ip] %> -p device_common
